import { coffeetea, mnl_portfolio } from "../assets/link_address";
import logo from "../assets/mn_bg_white.ico";

const content_EN = () => {
  const content = document.createElement("article");
  const title = document.createElement("h1");
  title.textContent =
    "How the web app Coffee or Tea for controlling budget expenses works";

  const firstParr = document.createElement("div");
  const enlaceInit = document.createElement("a");
  enlaceInit.setAttribute("href", coffeetea);
  enlaceInit.setAttribute("target", "_blank");
  enlaceInit.setAttribute("rel", "noopener noreferrer");
  enlaceInit.textContent = `${coffeetea}`;
  content.appendChild(enlaceInit);

  const txt1 = document.createElement("p");
  txt1.textContent =
    "is a React application designed as a purely client-side application, which means that it runs entirely in the user's browser without requiring a backend server for its core functionality.";

  const subtitle1 = document.createElement("p");
  subtitle1.className = "subtitle";
  subtitle1.textContent = "Complete data ownership and privacy.";

  const txt2 = document.createElement("p");
  txt2.textContent =
    "For persistent data storage, I chose a user-centric approach using file export and import functions. This method ensures that all data remains under the user's control, as it is stored locally on their device in files that they can manage, transfer, or copy.";

  const subtitle2 = document.createElement("p");
  subtitle2.className = "subtitle";
  subtitle2.textContent = "Features";

  const arrayFeatures = [
    "Each project or control can be created, modified, read, or deleted and temporarily stored locally (localStorage).",
    "Data input validation",
    "Expenses can be entered manually using an income table.",
    "The income table allows simple arithmetic operations to be calculated.",
    "The entry of expense categories includes a suggested list that allows for the uniformity necessary for subsequent data grouping. This list includes English, Spanish, and Portuguese. The language is defined by the language selected on the page when creating the new control.",
    "Users can enter their own expense categories, but must ensure consistency.",
    "You can create projects or controls with or without dates for specific activities.",
    "The visualization module allows you to group, sort, and graph data.",
    "In the examples module, there are three models to illustrate how the data is displayed.",
    "The displayed data can be printed in PDF files.",
  ];

  const exp_imp = [
    "Create a new control or project.",
    "Add at least one line of expenses.",
    "Save and export it.",
    "Use it in Excel or Drive spreadsheets, or simply keep it or transfer it.",
    "Add expense data without altering the file structure and do not change the date format",
    `The aspects to consider are: the date format must be "yyyy-MM-dd", the separator in numbers with decimals must be a period (.), and the CSV file must use a comma (,) as the separator. Files that use a semicolon as the separator will be rejected.`,
    "This way, you can import it back into the website to continue editing or simply view it.",
    "The imported file will overwrite the previous file, subject to user confirmation.",
  ];

  const tools = [
    "The table with multiple input rows-cells was designed entirely using React components interaction, where each cell in each row dynamically renders an input field and manages its own state through component-level state. This approach allows for individual row-cell level editing.",
    "Each project and its corresponding expenses were created with a class constructor. The constructor initializes the object's properties, ensuring that every new project or expense entry starts with a defined and consistent structure. This approach  improves code reliability and maintainability.",
    "To manage categories, a combination of Set for uniqueness (prevents duplicate entries) and Map for data association (to store key-value pairs) was used.",
    "The dates were handled using date-fns.",
    "React-router-dom was used to navigate within the app, and URL parameters were also used in the routes to pass variables or data between routes.",
    "All data manipulation tasks (grouping, sorting, summing, and graphical representation) were performed on the client side using D3.js.",
    "The PDF files were generated by combining the @react-pdf/renderer library to render structured data and dynamic content, while dom-to-image was used to capture and embed graphical elements. This method leverages the accuracy of react-pdf for text and layout, while ensuring that complex visualizations are preserved through image conversion.",
  ];

  content.appendChild(title);
  content.appendChild(firstParr);
  firstParr.appendChild(enlaceInit);
  firstParr.appendChild(txt1);
  content.appendChild(subtitle1);
  content.appendChild(txt2);
  content.appendChild(subtitle2);

  arrayFeatures.forEach((e) => {
    const span = document.createElement("span");
    span.textContent = "\u25E6";

    const div = document.createElement("div");
    const text = document.createElement("p");
    text.textContent = e;

    content.appendChild(div);
    div.appendChild(span);
    div.appendChild(text);
  });

  const enlace = document.createElement("a");
  enlace.className = "locateEnlace";
  enlace.setAttribute("href", coffeetea);
  enlace.setAttribute("target", "_blank");
  enlace.setAttribute("rel", "noopener noreferrer");
  enlace.textContent = `try ${coffeetea}`;
  content.appendChild(enlace);

  const divAdit = document.createElement("div");
  const text = document.createElement("p");
  text.textContent =
    "To use the option to import data from a CSV file, proceed as follows:";
  content.appendChild(divAdit);
  divAdit.className = "sublist";
  divAdit.appendChild(text);

  exp_imp.forEach((e) => {
    const span = document.createElement("span");
    span.textContent = "\u2B29";

    const div = document.createElement("div");
    div.className = "sublist";
    const text = document.createElement("p");
    text.textContent = e;

    content.appendChild(div);
    div.appendChild(span);
    div.appendChild(text);
  });

  const subtitle3 = document.createElement("p");
  subtitle3.className = "subtitle";
  subtitle3.textContent = "Design highlights";
  content.appendChild(subtitle3);

  tools.forEach((e) => {
    const span = document.createElement("span");
    span.textContent = "\u25E6";

    const div = document.createElement("div");
    const text = document.createElement("p");
    text.textContent = e;

    content.appendChild(div);
    div.appendChild(span);
    div.appendChild(text);
  });

  const enlace2 = document.createElement("a");
  enlace2.className = "locateEnlace";
  enlace2.setAttribute("href", coffeetea);
  enlace2.setAttribute("target", "_blank");
  enlace2.setAttribute("rel", "noopener noreferrer");
  enlace2.textContent = `try ${coffeetea}`;
  content.appendChild(enlace2);

  const footer = document.createElement("footer");
  const mn_logo = new Image();
  mn_logo.src = logo;
  const img = document.createElement("img");
  img.setAttribute("src", mn_logo.src);
  img.setAttribute("alt", "maria nelly lopez logo");
  img.setAttribute("width", "30px");
  img.setAttribute("height", "30px");
  const copy = document.createElement("p");
  copy.textContent = "\u00A9 2025 marianellylopez";

  const contactme = document.createElement("a");
  contactme.setAttribute("href", mnl_portfolio);
  contactme.setAttribute("target", "_blank");
  contactme.setAttribute("rel", "noopener noreferrer");
  contactme.textContent = "Contact Me for Developer Stuff";

  content.appendChild(footer);
  footer.appendChild(img);
  footer.appendChild(copy);
  footer.appendChild(contactme);

  return content;
};

export { content_EN };
